import type { ProjectState } from '@/store/types'
import { clipDur } from '@/lib/utils'
import { Renderer } from './renderer'

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 5_000)
}

function buildAttributions(state: ProjectState): string {
  const lines = [
    `# attributions.md`,
    ``,
    `**Project:** ${state.settings.name}  `,
    `**Exported:** ${new Date().toISOString()}  `,
    `**Resolution:** ${state.settings.width}×${state.settings.height} @ ${state.settings.fps} fps  `,
    ``,
    `## Media assets`,
    ``,
  ]

  if (state.assets.length === 0) {
    lines.push('No external media assets used in this project.')
  } else {
    for (const asset of state.assets) {
      const size = (asset.size / 1024).toFixed(0)
      const src = asset.sourceName ? ` — source: ${asset.sourceName}` : ''
      lines.push(`- **${asset.name}** (${asset.type}, ${size} KB)${src}`)
    }
  }

  lines.push(``, `---`, `*Generated by HurrCut. All media used under their respective licenses.*`)
  return lines.join('\n')
}

export async function exportProject(
  state: ProjectState,
  onProgress: (pct: number) => void,
): Promise<void> {
  const duration = state.clips.reduce((m, c) => Math.max(m, c.start + clipDur(c)), 0)
  if (duration <= 0) throw new Error('No clips to export')

  if (!window.MediaRecorder) throw new Error('MediaRecorder API not available in this browser')

  const { width, height, fps } = state.settings

  // Dedicated export canvas at full project resolution
  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height
  const renderer = new Renderer(canvas)

  // Warm up video elements so they start buffering
  for (const asset of state.assets) {
    if (asset.type === 'video' && asset.url) renderer.getVideoEl(asset)
  }

  const mimeType = MediaRecorder.isTypeSupported('video/webm;codecs=vp9')
    ? 'video/webm;codecs=vp9'
    : 'video/webm'

  const stream = canvas.captureStream(fps)
  const recorder = new MediaRecorder(stream, { mimeType })
  const chunks: BlobPart[] = []
  recorder.ondataavailable = (e) => { if (e.data.size > 0) chunks.push(e.data) }

  await new Promise<void>((resolve, reject) => {
    recorder.onstop = () => resolve()
    recorder.onerror = (e) => reject(new Error(String(e)))
    recorder.start(100) // chunk every 100 ms

    const totalFrames = Math.ceil(duration * fps)
    const frameDuration = 1000 / fps
    let frame = 0

    const nextFrame = () => {
      const t = frame / fps
      if (t > duration) {
        recorder.stop()
        return
      }

      // Seek all video clips (best-effort; render proceeds regardless)
      renderer.seekAll(state.clips, state.assets, t)
        .then(() => renderer.render(state.clips, state.assets, t, state.settings))
        .catch(() => renderer.render(state.clips, state.assets, t, state.settings))

      onProgress(Math.round((frame / totalFrames) * 95))
      frame++
      setTimeout(nextFrame, frameDuration)
    }

    nextFrame()
  })

  const safeName = (state.settings.name || 'export').replace(/[^a-z0-9_\-. ]/gi, '_').trim()
  downloadBlob(new Blob(chunks, { type: mimeType }), `${safeName}.webm`)
  downloadBlob(new Blob([buildAttributions(state)], { type: 'text/markdown' }), 'attributions.md')

  renderer.dispose()
  onProgress(100)
}
